<a href="https://colab.research.google.com/github/kevinkemps/hw3_image_classification/blob/main/hw_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.datasets import cifar10
# load the dataset
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

170498071/170498071 [==============================] - 13s 0us/step


In [2]:
from skimage.color import rgb2gray
# convert to grayscale images
X_train = rgb2gray(X_train)
X_test = rgb2gray(X_test)

In [3]:
# Preprocessing: Normalize the images.
train_images = (X_train / 255)
test_images = (X_test / 255)

In [5]:
import math
import pandas as pd
import keras
from keras import models, layers, optimizers, regularizers
import numpy as np
import random
from sklearn import model_selection, preprocessing
import tensorflow as tf
from tqdm import tqdm
import matplotlib.pyplot as plt
from keras.models import Model, Sequential
from keras.layers import Dense, Dropout

In [19]:
model = Sequential([Dense(64, input_shape=(1024,), activation='relu'),
                    Dense(32, activation='relu'),
                    Dense(10, activation='softmax')])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 64)                65600     
                                                                 
 dense_4 (Dense)             (None, 32)                2080      
                                                                 
 dense_5 (Dense)             (None, 10)                330       
                                                                 
Total params: 68010 (265.66 KB)
Trainable params: 68010 (265.66 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
# Compile model
model.compile(optimizer='sgd', loss='categorical_crossentropy',metrics=['accuracy'],)

In [9]:
flatten_train_images = train_images.reshape((-1, 32*32))
print(flatten_train_images)
flatten_test_images = test_images.reshape((-1, 32*32))

print("Train image shape: ", train_images.shape, "Flattened image shape: ", flatten_train_images.shape)

[[0.00094478 0.00069651 0.00073917 ... 0.00288547 0.00188483 0.00149397]
 [0.00265795 0.00206983 0.00159267 ... 0.0020847  0.00209903 0.00209024]
 [0.00392157 0.00389081 0.00389081 ... 0.0012821  0.00128536 0.00130074]
 ...
 [0.00233329 0.00233206 0.00234082 ... 0.00074571 0.00061489 0.00043572]
 [0.00320517 0.00315792 0.00314254 ... 0.002849   0.00290949 0.00291723]
 [0.00353281 0.00365257 0.00363503 ... 0.00272413 0.00251989 0.00250451]]
Train image shape:  (50000, 32, 32) Flattened image shape:  (50000, 1024)


In [10]:
32*32

1024

In [15]:
from keras.utils import to_categorical

print("Train image shape: ", train_images.shape, "Flattened image shape: ", flatten_train_images.shape)

Train image shape:  (50000, 32, 32) Flattened image shape:  (50000, 1024)


In [22]:
model.fit(flatten_train_images, to_categorical(y_train), epochs=10, batch_size=256,)


Epoch 1/10
196/196 [==============================] - 2s 3ms/step - loss: 2.3023 - accuracy: 0.1088
Epoch 2/10
196/196 [==============================] - 1s 3ms/step - loss: 2.3021 - accuracy: 0.1210
Epoch 3/10
196/196 [==============================] - 1s 3ms/step - loss: 2.3021 - accuracy: 0.1229
Epoch 4/10
196/196 [==============================] - 1s 3ms/step - loss: 2.3021 - accuracy: 0.1273
Epoch 5/10
196/196 [==============================] - 1s 3ms/step - loss: 2.3020 - accuracy: 0.1256
Epoch 6/10
196/196 [==============================] - 1s 3ms/step - loss: 2.3020 - accuracy: 0.1354
Epoch 7/10
196/196 [==============================] - 1s 3ms/step - loss: 2.3020 - accuracy: 0.1446
Epoch 8/10
196/196 [==============================] - 1s 3ms/step - loss: 2.3020 - accuracy: 0.1355
Epoch 9/10
196/196 [==============================] - 1s 4ms/step - loss: 2.3020 - accuracy: 0.1279
Epoch 10/10
196/196 [==============================] - 1s 4ms/step - loss: 2.3020 - accuracy: 0.1221

In [23]:

# Evaluate your model's performance on the test data
performance = model.evaluate(flatten_test_images, to_categorical(y_test))
print("Accuracy on Test samples: {0}".format(performance[1]))

313/313 [==============================] - 1s 3ms/step - loss: 2.3019 - accuracy: 0.1179
Accuracy on Test samples: 0.11789999902248383
